### ISSUE TITLE
feature request: 数学表达式预览

### ISSUE THREAD

**Issue by zhangyufei49** [yrming/vscode-yuque#1]
markdown 文档希望支持数学表达式预览。现版本 0.0.9 还不支持。
或者可以使用 vscode 自带的 markdown 预览也行，那个支持数学表达式预览。

**Comment by yrming** [comment]
> markdown 文档希望支持数学表达式预览。现版本 0.0.9 还不支持。 或者可以使用 vscode 自带的 markdown 预览也行，那个支持数学表达式预览。

@FlyingFishBird 下个版本支持，谢谢使用。

**Comment by yrming** [comment]
> markdown 文档希望支持数学表达式预览。现版本 0.0.9 还不支持。 或者可以使用 vscode 自带的 markdown 预览也行，那个支持数学表达式预览。

@FlyingFishBird 已支持，请更新到最新版本。
