### ISSUE TITLE
not support remote ssh

### ISSUE THREAD

**Issue by tonyttz** [yrming/vscode-yuque#2]
install with remote ssh mode, yuque view always show loading...
![image](https://user-images.githubusercontent.com/62124884/145804425-cce1ac07-4990-4ba4-9a05-7ec162fc179e.png)

**Comment by yrming** [comment]
> install with remote ssh mode, yuque view always show loading... ![image](https://user-images.githubusercontent.com/62124884/145804425-cce1ac07-4990-4ba4-9a05-7ec162fc179e.png)

@tonyttz The api endpoint of @yuque/sdk is **https://www.yuque.com/api/v2/**, so please check if this domain name is in the whitelist of your server.

**Comment by tonyttz** [comment]
> 

![image](https://user-images.githubusercontent.com/62124884/145932380-b76a8c5a-dcc5-4349-92f5-ca2a2183bb85.png)

**Comment by yrming** [comment]
> install with remote ssh mode, yuque view always show loading... ![image](https://user-images.githubusercontent.com/62124884/145804425-cce1ac07-4990-4ba4-9a05-7ec162fc179e.png)

@tonyttz  I have reproduced this problem and it will be fixed soon.

**Comment by yrming** [comment]
@tonyttz Hi, I am sorry that it took too long. It has been fixed now, please update to the latest version.
