### ISSUE TITLE
后面会考虑支持一下文档增删改吗？

### ISSUE THREAD

**Issue by gqzw** [yrming/vscode-yuque#6]
rt，
如果可以在vscode编辑文档，那就完美了

**Comment by yrming** [comment]
@didnhdj  <img width="421" alt="image" src="https://user-images.githubusercontent.com/5096365/192926180-e7d90d24-26ae-493c-9b6d-68932699765e.png">

**Comment by didnhdj** [comment]
@yrming 图片加载不出来

**Comment by yrming** [comment]
@didnhdj 可以简单提供一个复现的文档吗？

**Comment by gqzw** [comment]
不好意思，之前以为这个地方是修改文件名，现在看到了可以编辑，非常感谢！！！

**Comment by yrming** [comment]
我优化一下，感谢你的使用。😄

**Comment by yrming** [comment]
>![image](https://user-images.githubusercontent.com/5096365/193060457-527d764d-618e-43fe-9883-43e7fe3f0f7c.png)

同时，因为如上语雀API的限制，如果你的文档创建和编辑是使用VSCode插件来操作的，那么后续的维护也最好使用插件来操作。

祝开心。

**Comment by gqzw** [comment]
今天我也看了一遍语雀的文档，本来计划自己开发的，看到插件市场正好已有一个相同功能的，甚是惊喜，非常感谢贡献了一个好用的插件！！！
